# Site settings
title: Blog
description: > # this means to ignore newlines until "baseurl:"
  Alex Interrante-Grant's personal blog for tech tutorials, lessons learned, and new ideas.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://ainterr.github.io" # the base hostname & protocol for your site
main_site: "http://ainterr.github.io"
paginate: 1
permalink: none
